name: Docker container

on:
  - push

jobs:
  run_in_docker_container:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/usr/local/bin/node"
          args: '-v'
      - name: Send message to slack
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_MESSAGE: Test message from commit ${{ github.sha }}

          