name: File creation and push

on:
  - push

jobs:
  create-file-and-push:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Create File with random number
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}".git
          git config --global user.email "testEmail@test.com"
          git config --global user.name "testName"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          git add -a
          git commit -m "create a new file"
          git push
