name: Matrix

on:
  - push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Log version
        run: node -v
      - name: Change node v
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log version
        run: node -v